# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/gd14470/sdsoc_workspace/lab1/Release/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_auto_pc_1/zed_auto_pc_1.xci
# IP: The module: 'zed_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gd14470/sdsoc_workspace/lab1/Release/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_auto_pc_1/zed_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_auto_pc_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/gd14470/sdsoc_workspace/lab1/Release/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_auto_pc_1/zed_auto_pc_1.xci
# IP: The module: 'zed_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gd14470/sdsoc_workspace/lab1/Release/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_auto_pc_1/zed_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_auto_pc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
