# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/workspace_sdx/lab_1/Release/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_mmult_1_0/zed_mmult_1_0.xci
# IP: The module: 'zed_mmult_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/workspace_sdx/lab_1/Release/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_mmult_1_0/constraints/a1_mmult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_mmult_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Xilinx/workspace_sdx/lab_1/Release/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_mmult_1_0/zed_mmult_1_0.xci
# IP: The module: 'zed_mmult_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/workspace_sdx/lab_1/Release/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_mmult_1_0/constraints/a1_mmult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_mmult_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
