# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Xilinx/workspace_sdx/lab_1/Release/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_3_0/zed_proc_sys_reset_3_0.xci
# IP: The module: 'zed_proc_sys_reset_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/workspace_sdx/lab_1/Release/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_3_0/zed_proc_sys_reset_3_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_proc_sys_reset_3_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Xilinx/workspace_sdx/lab_1/Release/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_3_0/zed_proc_sys_reset_3_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_proc_sys_reset_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Xilinx/workspace_sdx/lab_1/Release/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_3_0/zed_proc_sys_reset_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_proc_sys_reset_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Xilinx/workspace_sdx/lab_1/Release/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_3_0/zed_proc_sys_reset_3_0.xci
# IP: The module: 'zed_proc_sys_reset_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/workspace_sdx/lab_1/Release/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_3_0/zed_proc_sys_reset_3_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_proc_sys_reset_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Xilinx/workspace_sdx/lab_1/Release/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_3_0/zed_proc_sys_reset_3_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_proc_sys_reset_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Xilinx/workspace_sdx/lab_1/Release/_sds/p0/vivado/prj/prj.srcs/sources_1/bd/zed/ip/zed_proc_sys_reset_3_0/zed_proc_sys_reset_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zed_proc_sys_reset_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
