# This file was automatically generated by SDx
write_user_impl_clock_constraint "" "clk_wiz_0_clk_out1 {is_user_set false clk_id 2 freq 100.000000} clk_wiz_0_clk_out2 {is_user_set false clk_id 1 freq 142.857142} clk_wiz_0_clk_out3 {is_user_set false clk_id 0 freq 166.666666} clk_wiz_0_clk_out4 {is_user_set false clk_id 3 freq 200.000000}" "" "../../../output"
